Task_1_1_2
VisTheB/OOP pull request #4
Opened 2024-09-16 08:15 UTC by VisTheB

Добавила первую версию блэкджека. Тесты пока только для карт
(Чтобы пройти мягкий дедлайн...)

2024-09-16 16:43 UTC, galinabykova requested changes
мягкий засчитан)

2024-09-16 16:43 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/basargina/Game.java
> +        if (dealer.getPlayerHand().countHandSum() > 21) {
для 21 лучше сделать константную переменную, чтобы было более читаемо и можно было менять

2024-09-16 16:43 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/basargina/Game.java
> +        else if (human.getPlayerHand().countHandSum() > dealer.getPlayerHand().countHandSum()) {
human.getPlayerHand().countHandSum() 3 раза встречается в этом методе, возможно, стоит сделать переменную

2024-09-16 16:43 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/basargina/deck/Deck.java
> +    public ArrayList<Card> getCards() {
судя по коду, этот метод нужен для того, чтобы переложить карты из одной колоды в другую. Мне кажется, лучше сделать метод по перекладыванию карт, так как он даст меньше свободы вне класса

2024-09-16 16:43 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/basargina/players/Player.java
> +    public void take(Deck deck, Deck droppedDeck, boolean isDealer, boolean isHasClosed) {
так как ты используешь наследование, логично будет не делать отдельный параметр isDealer, а сделать переопределение в классе Deater. Также isHasClosed, наверное, должно быть частью состояния дилера

2024-09-21 14:47 UTC, VisTheB commented
Тесты для game в процессе

2024-09-22 07:57 UTC, VisTheB commented
Чтобы покрытие для Game стало больше, надо добавить тестов с другими вариантами вывода? (По типу "ты проиграл", "дилер выиграл")

2024-09-22 11:03 UTC, galinabykova requested changes
нужно избавиться от публичных не константных полей. Поля класса должны быть доступны только в классе и, может быть, в тестах (хотя это нежелательно), для этого достаточно package private

в дальнейшем, пожалуйста, не удаляй мои комментарии, я опираюсь на них при повторной проверке

2024-09-22 11:03 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/basargina/deck/Suit.java
> +    final String suitName;
можно сделать private

2024-09-22 11:03 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/basargina/deck/Rank.java
> +    final int rankValue;
можно сделать private

2024-09-22 11:04 UTC, galinabykova commented
> Чтобы покрытие для Game стало больше, надо добавить тестов с другими вариантами вывода? (По типу "ты проиграл", "дилер выиграл")

да, ты можешь в своей ide запустить тесты с покрытием и посмотреть, какие именно строчки не покрыты

2024-09-22 15:32 UTC, galinabykova approved these changes

2024-09-22 16:05 UTC, merged