Task_1_1_3
VisTheB/OOP pull request #5
Opened 2024-09-29 15:43 UTC by VisTheB

Первая версия (без ExpressionParser.test)

2024-09-30 02:59 UTC, galinabykova requested changes
мягкий засчитан)

2024-09-30 02:59 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +            throw new RuntimeException("Unexpected: " + (char) ch);
а почему RuntimeException?

2024-09-30 02:59 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/actions/Add.java
> +    public String print() {
знаю, что у вас в задании такая сигнатура, но на всякий случай проговорю, что обычно для строкового представления класса переопределяют метод toString. Его используют библиотечные классы (например, System.out.println)

2024-09-30 02:59 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/Main.java
> +    private static Map<String, Double> parseVariables(String input) {
можно было бы перенести этот метод в Expression и сделать метод eval(String) с телом 
`eval(parseVariables(string))`
но твой вариант вроде тоже норм

2024-09-30 02:59 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/data/Variable.java
> +    public double eval(Map<String, Double> variables) {
нужно уточнить в документации, что будет, если переменной не будет в словаре. Почему ты выбрала такое поведение, а не, например, исключение?

2024-09-30 02:59 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/basargina/data/VariableTest.java
> +    void testEval() {
сделай ещё тест на ситуацию, когда нет в словаре переменной

2024-10-04 02:58 UTC, VisTheB commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +            throw new RuntimeException("Unexpected: " + (char) ch);
Если введено например некорректное выражение

2024-10-04 03:10 UTC, VisTheB commented on Task_1_1_3/src/main/java/ru/nsu/basargina/data/Variable.java
> +    public double eval(Map<String, Double> variables) {
Да, здесь лучше будет исключение мне кажется

2024-10-06 09:09 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +            throw new RuntimeException("Unexpected: " + (char) ch);
RuntimeException - это непроверяемое исключение,  почему ты используешь его, а не, например, Exception

2024-10-06 09:12 UTC, galinabykova requested changes
reviewdog

2024-10-06 09:12 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/data/Expression.java
> +    public abstract String toString();
сюда можно добавить Override

2024-10-06 14:39 UTC, VisTheB commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +            throw new RuntimeException("Unexpected: " + (char) ch);
Тогда лучше использовать try/catch ?

2024-10-06 15:33 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +            throw new RuntimeException("Unexpected: " + (char) ch);
не, есть два разных вида исключений: проверяемые и непроверяемые. Если бы ты использовала проверяемые, надо было бы в сигнатуру throws ... Твой вариант адекватен, но надо это обосновать. Давай на теоретической сдаче дообсуждаем это, менять не надо.

2024-10-06 15:44 UTC, VisTheB commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +            throw new RuntimeException("Unexpected: " + (char) ch);
Блин я уже изменила

2024-10-06 16:00 UTC, galinabykova requested changes
reviewdog

2024-10-06 16:00 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +                throw new Exception("Unexpected: " + (char) ch);
так делать не надо. Основная идея исключений в том, что ты разделяешь место, где обрабатываешь исключение, и место, где его обнаруживаешь. Если ты знаешь, что делать в методе, где бросаешь исключение, тебе не нужно исключение, достаточно иф, ведь исключения очень много времени занимают. Тут тебе, скорее всего, надо убрать try-catch, оставить throw и добавить в сигнатуру метода throws Exception

2024-10-07 02:29 UTC, galinabykova approved these changes

2024-10-07 02:29 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/basargina/ExpressionParser.java
> +    public Expression parse() {
тут такая же проблема, но ты разобралась, так что исправлять не надо

2024-10-14 13:32 UTC, merged