Task_1_2_1
VisTheB/OOP pull request #6
Opened 2024-10-14 13:29 UTC by VisTheB

Пока нету топологической сортировки

2024-10-14 14:56 UTC, galinabykova requested changes
мягкий засчитан)

2024-10-14 14:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/basargina/Graph.java
> +public interface Graph<T> {
в этой лабе надо сделать объектную модель, надо, чтобы в ней хотя бы вершины и рёбра были

2024-10-14 14:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/basargina/Graph.java
> +public interface Graph<T> {
то есть надо сделать отдельные классы для вершин и рёбер

2024-10-14 14:56 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/basargina/AdjacencyList.java
> +            System.out.println("Error reading from file: " + e.getMessage());
тут лучше пробросить исключение дальше, так как непонятно, что делать. Используй wrapping exception

2024-10-20 09:09 UTC, VisTheB commented
Я еще не понимаю, что джавадог имеет в виду под "'annotation array initialization' child has incorrect indentation level 12, expected level should be 8."

2024-10-20 12:58 UTC, galinabykova requested changes
не увидела топологическую сортировку

2024-10-20 12:58 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/basargina/AdjacencyList.java
> +            throw new Exception("Error reading from file");
нужно ещё старое ислючение пробросить, добавить e в конструктор, как тут
![image](https://github.com/user-attachments/assets/ee4c121d-1a86-4fb5-b967-d9e457739d60)
https://stackoverflow.com/questions/28972893/what-is-exception-wrapping-in-java

2024-10-21 04:46 UTC, galinabykova commented
> Я еще не понимаю, что джавадог имеет в виду под "'annotation array initialization' child has incorrect indentation level 12, expected level should be 8."

это про отступы (количество пробелов в начале строки)

2024-10-21 04:48 UTC, galinabykova requested changes
reviewdog

2024-10-21 05:59 UTC, galinabykova approved these changes

2024-10-27 14:51 UTC, merged