Task_1_3_1
VisTheB/OOP pull request #8
Opened 2024-11-08 17:19 UTC by VisTheB

Добавила первую версию. Я сначала считывала файл по блокам и использовала алгоритм поиска КМП, но из-за того, что по блокам считывание, то не все вхождения находились. Поэтому пришлось изменить всё на просто считывание по символам и сравнение с шаблоном

2024-11-09 14:58 UTC, galinabykova requested changes
мягкий засчитан)

2024-11-09 14:58 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/basargina/SubstringSearcherTest.java
> +        long size = 10 * 1024 * 1024; // 10 MB
Нужно, чтобы размер был хотя бы больше оперативной памяти твоего ноутбука.Так ты сможешь проверить, что действительно корректно написала метод. 

Также обрати внимание, что после равно у тебя int. В java численные литералы по умолчанию int. Чтобы сделать long надо добавить постфикс L (н-р, 1000000000L)

2024-11-09 14:58 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/basargina/SubstringSearcherTest.java
> +        List<Integer> results = findSubstringInFile(tempFile.getPath(), pattern);
лучше сделать большой тест так,чтобы в нём было мало вхождений, а то результат может в память не влезти

2024-11-09 14:58 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/basargina/SubstringSearcher.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
хорошим тоном считается указание кодировки, даже если тебе нужна кодировка, выбираемая по умолчанию

2024-11-09 14:58 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/basargina/SubstringSearcherTest.java
> +        File tempFile = File.createTempFile("tempFile", ".txt");
у тебя интересное решение с записью файлов, выглядит интересно. Но писать один и тот же файл не хочется каждый раз (ситуация с большим файлом исключение - ты просто не сможешь запушить его на гитхаб, поэтому его надо генерировать), а ещё в этой лабе хорошо бы познакомиться с ресурсами. Ресурсы - это файлы, включаемые в сборку. Так как они включены в сборку, тебе не нужно будет таскать их с jarом, они будут в самом jar. 

Посмотри, как сделано тут
https://sky.pro/wiki/java/poluchenie-puti-k-resursu-v-jar-fayle-java-resheniya-i-oshibki/
в статическом методе можно написать НазваниеКласса.class вместо getClass

Сделай один тест с чтением из ресурсов. Для этого тебе нужно будет изменить интерфейс твоего метода. Предлагается использовать иерархичность потоков ввода и вынести поиск подстроки в метод, который будет читать из InputStream или Reader

2024-11-09 14:58 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/basargina/SubstringSearcherTest.java
> +        File tempFile = File.createTempFile("tempFile", ".txt");
а для чтения из файла и из ресурса можно сделать отдельные методы

2024-11-15 08:56 UTC, VisTheB commented
Я снова переделала алгоритм поиска. В моем прошлом варианте через строки тест с большим файлом работал слишком медленно и неправильно. Поэтому теперь я просто массив чаров использую и тоже методом окна двигаю/сравниваю

2024-11-15 09:03 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/basargina/SubstringSearcher.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/FileReader.html#%3Cinit%3E(java.io.File,java.nio.charset.Charset)

2024-11-15 09:09 UTC, galinabykova requested changes

2024-11-15 09:09 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/basargina/SubstringSearcherTest.java
> +        InputStream in = getClass().getResourceAsStream("/test.txt");
мне кажется, прочитать файл, чтобы потом его записать в другое место, чтобы потом из другого места его прочёл метод - слишком сложное решение. Сделай так, чтобы у тебя читалось прямо из ресурса без временных файлов.

Для этого тебе нужно будет изменить интерфейс твоего метода. Предлагается использовать иерархичность потоков ввода и вынести поиск подстроки в метод, который будет читать из InputStream или Reader

2024-11-15 09:09 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/basargina/SubstringSearcherTest.java
> +        InputStream in = getClass().getResourceAsStream("/test.txt");
то есть можно будет сделать метод, который будет принимать ридер или поток ввода и искать индесы. А чтение файла/ресурса перенести в отдельные методы или вообще уже в тестах делать

2024-11-15 09:09 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/basargina/SubstringSearcher.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
@VisTheB

2024-11-17 11:59 UTC, galinabykova approved these changes

2024-11-17 12:27 UTC, merged