Task_1_4_1
VisTheB/OOP pull request #9
Opened 2024-11-23 10:21 UTC by VisTheB

Первая версия

2024-11-24 05:47 UTC, galinabykova requested changes

2024-11-24 05:47 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/basargina/RecordBook.java
> +        long fivesCnt = grades.stream().filter(Grade::isFive).count();
некоторые предметы идут несколько семестров, но в диплом идёт только последняя оценка

2024-11-24 05:47 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/basargina/Grade.java
> +    public Grade(String subjectName, int score, WorkType type, int semester) {
мне кажется, стоит добавить проверку корректности входных данных

2024-11-24 18:25 UTC, galinabykova requested changes

2024-11-24 18:25 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/basargina/RecordBook.java
> +    private List<Grade> getLastSemesterGrades() {
сделай этот метод без циклов (только StreamAPI)

2024-11-24 18:25 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/basargina/Grade.java
> +            throw new Exception("Score must be between 2 and 5.");
мне кажется, лучше будет использовать более специализированное исключение. Предлагаю тебе создать своё (это быстро). Это позволит удобно отделять исключения по типам

2024-11-25 04:16 UTC, VisTheB commented on Task_1_4_1/src/main/java/ru/nsu/basargina/Grade.java
> +            throw new Exception("Score must be between 2 and 5.");
То есть для каждого set своё исключение? Или одно для всех?

2024-11-25 06:11 UTC, VisTheB commented on Task_1_4_1/src/main/java/ru/nsu/basargina/Grade.java
> +            throw new Exception("Score must be between 2 and 5.");
@galinabykova

2024-11-25 06:35 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/basargina/Grade.java
> +            throw new Exception("Score must be between 2 and 5.");
я имею ввиду создать свой класс исключений. В идеале иерархию, но одного в этой лабе будет достаточно

2024-11-25 06:35 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/basargina/Grade.java
> +            throw new Exception("Score must be between 2 and 5.");
и бросать объекты этого класса

2024-11-25 06:35 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/basargina/Grade.java
> +            throw new Exception("Score must be between 2 and 5.");
то есть можешь просто создать свой тип исключений-наследник Exception и его бросать

2024-11-25 15:25 UTC, galinabykova approved these changes

2024-11-25 15:29 UTC, merged